// <auto-generated />
using System;
using HastaneRezerv.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HastaneRezerv.Migrations
{
    [DbContext(typeof(HastaneContext))]
    [Migration("20231219022035_InitialCreated")]
    partial class InitialCreated
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HastaneRezerv.Models.Aktiflik", b =>
                {
                    b.Property<int>("AktiflikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AktiflikId"), 1L, 1);

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AktiflikId");

                    b.ToTable("Aktiflik");
                });

            modelBuilder.Entity("HastaneRezerv.Models.AnaBilimDali", b =>
                {
                    b.Property<int>("AnaBilimDaliId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnaBilimDaliId"), 1L, 1);

                    b.Property<int>("AktiflikId")
                        .HasColumnType("int");

                    b.Property<string>("AnaBilimDaliAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AnaBilimDaliId");

                    b.HasIndex("AktiflikId");

                    b.ToTable("AnaBilimDali");
                });

            modelBuilder.Entity("HastaneRezerv.Models.Doktor", b =>
                {
                    b.Property<int>("DoktorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DoktorId"), 1L, 1);

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AktiflikId")
                        .HasColumnType("int");

                    b.Property<int>("AnaBilimDaliId")
                        .HasColumnType("int");

                    b.Property<int>("PoliklinikId")
                        .HasColumnType("int");

                    b.Property<int>("TcNo")
                        .HasColumnType("int");

                    b.HasKey("DoktorId");

                    b.HasIndex("AktiflikId");

                    b.HasIndex("AnaBilimDaliId");

                    b.HasIndex("PoliklinikId");

                    b.ToTable("Doktor");
                });

            modelBuilder.Entity("HastaneRezerv.Models.Hastane", b =>
                {
                    b.Property<int>("HastaneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HastaneId"), 1L, 1);

                    b.Property<int>("AktiflikId")
                        .HasColumnType("int");

                    b.Property<string>("HastaneAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HastaneId");

                    b.HasIndex("AktiflikId");

                    b.ToTable("Hastane");
                });

            modelBuilder.Entity("HastaneRezerv.Models.Kullanici", b =>
                {
                    b.Property<int>("KullaniciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KullaniciId"), 1L, 1);

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AktiflikId")
                        .HasColumnType("int");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TcNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TekrarSifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnvanId")
                        .HasColumnType("int");

                    b.HasKey("KullaniciId");

                    b.HasIndex("AktiflikId");

                    b.HasIndex("UnvanId");

                    b.ToTable("Kullanici");
                });

            modelBuilder.Entity("HastaneRezerv.Models.Poliklinik", b =>
                {
                    b.Property<int>("PoliklinikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PoliklinikId"), 1L, 1);

                    b.Property<int>("AktiflikId")
                        .HasColumnType("int");

                    b.Property<int>("HastaneId")
                        .HasColumnType("int");

                    b.Property<string>("PoliklinikAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PoliklinikId");

                    b.HasIndex("AktiflikId");

                    b.HasIndex("HastaneId");

                    b.ToTable("Poliklinik");
                });

            modelBuilder.Entity("HastaneRezerv.Models.Randevu", b =>
                {
                    b.Property<int>("RandevuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RandevuId"), 1L, 1);

                    b.Property<int>("AktiflikId")
                        .HasColumnType("int");

                    b.Property<int>("DoktorId")
                        .HasColumnType("int");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("RandevuId");

                    b.HasIndex("AktiflikId");

                    b.HasIndex("DoktorId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("Randevu");
                });

            modelBuilder.Entity("HastaneRezerv.Models.Unvan", b =>
                {
                    b.Property<int>("UnvanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UnvanId"), 1L, 1);

                    b.Property<string>("UnvanAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UnvanId");

                    b.ToTable("Unvan");
                });

            modelBuilder.Entity("HastaneRezerv.Models.AnaBilimDali", b =>
                {
                    b.HasOne("HastaneRezerv.Models.Aktiflik", "Aktiflik")
                        .WithMany("AnaBilimDali")
                        .HasForeignKey("AktiflikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aktiflik");
                });

            modelBuilder.Entity("HastaneRezerv.Models.Doktor", b =>
                {
                    b.HasOne("HastaneRezerv.Models.Aktiflik", null)
                        .WithMany("Doktor")
                        .HasForeignKey("AktiflikId");

                    b.HasOne("HastaneRezerv.Models.AnaBilimDali", "AnaBilimDali")
                        .WithMany("Doktor")
                        .HasForeignKey("AnaBilimDaliId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HastaneRezerv.Models.Poliklinik", "Poliklinik")
                        .WithMany("Doktor")
                        .HasForeignKey("PoliklinikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnaBilimDali");

                    b.Navigation("Poliklinik");
                });

            modelBuilder.Entity("HastaneRezerv.Models.Hastane", b =>
                {
                    b.HasOne("HastaneRezerv.Models.Aktiflik", "Aktiflik")
                        .WithMany("Hastane")
                        .HasForeignKey("AktiflikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aktiflik");
                });

            modelBuilder.Entity("HastaneRezerv.Models.Kullanici", b =>
                {
                    b.HasOne("HastaneRezerv.Models.Aktiflik", "Aktiflik")
                        .WithMany("Kullanici")
                        .HasForeignKey("AktiflikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HastaneRezerv.Models.Unvan", "Unvan")
                        .WithMany("Kullanici")
                        .HasForeignKey("UnvanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aktiflik");

                    b.Navigation("Unvan");
                });

            modelBuilder.Entity("HastaneRezerv.Models.Poliklinik", b =>
                {
                    b.HasOne("HastaneRezerv.Models.Aktiflik", "Aktiflik")
                        .WithMany("Poliklinik")
                        .HasForeignKey("AktiflikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HastaneRezerv.Models.Hastane", "Hastane")
                        .WithMany("Poliklinik")
                        .HasForeignKey("HastaneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aktiflik");

                    b.Navigation("Hastane");
                });

            modelBuilder.Entity("HastaneRezerv.Models.Randevu", b =>
                {
                    b.HasOne("HastaneRezerv.Models.Aktiflik", "Aktiflik")
                        .WithMany("Randevu")
                        .HasForeignKey("AktiflikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HastaneRezerv.Models.Doktor", "Doktor")
                        .WithMany("Randevu")
                        .HasForeignKey("DoktorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HastaneRezerv.Models.Kullanici", "Kullanici")
                        .WithMany("Randevu")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aktiflik");

                    b.Navigation("Doktor");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("HastaneRezerv.Models.Aktiflik", b =>
                {
                    b.Navigation("AnaBilimDali");

                    b.Navigation("Doktor");

                    b.Navigation("Hastane");

                    b.Navigation("Kullanici");

                    b.Navigation("Poliklinik");

                    b.Navigation("Randevu");
                });

            modelBuilder.Entity("HastaneRezerv.Models.AnaBilimDali", b =>
                {
                    b.Navigation("Doktor");
                });

            modelBuilder.Entity("HastaneRezerv.Models.Doktor", b =>
                {
                    b.Navigation("Randevu");
                });

            modelBuilder.Entity("HastaneRezerv.Models.Hastane", b =>
                {
                    b.Navigation("Poliklinik");
                });

            modelBuilder.Entity("HastaneRezerv.Models.Kullanici", b =>
                {
                    b.Navigation("Randevu");
                });

            modelBuilder.Entity("HastaneRezerv.Models.Poliklinik", b =>
                {
                    b.Navigation("Doktor");
                });

            modelBuilder.Entity("HastaneRezerv.Models.Unvan", b =>
                {
                    b.Navigation("Kullanici");
                });
#pragma warning restore 612, 618
        }
    }
}
